### ISSUE TITLE
[QUESTION] Does this equality check works as expected?

### ISSUE THREAD

**Issue by zoedsoupe** [jvfd3/DataStructure#1]
When we say about sets equality, we say that all elements of 2 sets are strictly equal, no matters in what position they are!

ex:
`{1,2,3}` == `{3,2,1}`

So, could you please explain me what did you do? I didn't get exactly your logic.

**Comment by jvfd3** [comment]
I check each element of each list with all elements of the other list (but breaking the loop if an element equality is found).
If all the elements of the first set are contained in the second set, the "hasSameElement1" variable will have the same value of the first list length. The same happens for the second list.
So, if "hasSameElement1" is equal to "hasSameElement2" (and both are bigger than zero), the sets are equal.

**Comment by zoedsoupe** [comment]
Oh, know I understand! Thank you for your explanation! I not used to with so many mutability on variables :)
