### ISSUE TITLE
[IMPROVEMENT] Why show pointer's addresses as integers?

### ISSUE THREAD

**Issue by zoedsoupe** [jvfd3/DataStructure#2]
In C, pointers addresses are addresses to physical memory, binary or hexadecimal representation in a nutshell (:

Although binary representation is more "canonical", numbers length will grow exponentially,
so I think hexadecimal fits better here!

if you want to print as a hexadecimal address, you have 2 options:
```c
printf("%x", pointer); // prints letters in lowercase, ex: ff

printf("%X", pointer); // prints letters in uppercarse, ex: 1A
```

Let me know if you want a PR, you'll solve by yourself or if you don't want to change this.

**Comment by jvfd3** [comment]
I don't think it's a big issue for now, but I changed it just in case. Thx.

**Comment by zoedsoupe** [comment]
No problem! Thxs for attention!
